import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { Header } from "@/components/shared/header";
import "./globals.css";
import { Providers } from "@/components/shared/providers";

import BreadcrumbLogic from "@/components/shared/breadcrumb";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const nunito = Nunito({
    subsets: ["cyrillic"],
    variable: "--font-nunito",
    weight: ["400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru" className="scroll-smooth">
            <body className={nunito.variable}>
                <Providers>
                    <main className="min-h-screen">
                        <Header />
                        <BreadcrumbLogic />
                        {children}
                    </main>
                </Providers>
            </body>
        </html>
    );
}
